# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = obj/Debug/DeusVultCore
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/libDeusVultCore.a
  DEFINES   += -DDEBUG
  INCLUDES  += -Ispine/spine-sfml/src -Ispine/spine-c/spine-c/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += 
  LIBS      += -llua5.1
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/Release/DeusVultCore
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/libDeusVultCore.a
  DEFINES   += -DNDEBUG
  INCLUDES  += -Ispine/spine-sfml/src -Ispine/spine-c/spine-c/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s
  LIBS      += -llua5.1
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/InputManager.o \
	$(OBJDIR)/ResourceManager.o \
	$(OBJDIR)/MapManager.o \
	$(OBJDIR)/EntityList.o \
	$(OBJDIR)/AnimatedSprite.o \
	$(OBJDIR)/SPRAnimation.o \
	$(OBJDIR)/Game.o \
	$(OBJDIR)/Entity.o \
	$(OBJDIR)/GameMap.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/Scripts.o \
	$(OBJDIR)/HUD.o \
	$(OBJDIR)/MovementComponent.o \
	$(OBJDIR)/NpcComponent.o \
	$(OBJDIR)/SensoryComponent.o \
	$(OBJDIR)/ControllerComponent.o \
	$(OBJDIR)/CombatComponent.o \
	$(OBJDIR)/SpineComponent.o \
	$(OBJDIR)/OutlineComponent.o \
	$(OBJDIR)/ScriptComponent.o \
	$(OBJDIR)/SpriteComponent.o \
	$(OBJDIR)/InteractionComponent.o \
	$(OBJDIR)/TransformComponent.o \
	$(OBJDIR)/MeshAttachment.o \
	$(OBJDIR)/Animation.o \
	$(OBJDIR)/SkeletonJson.o \
	$(OBJDIR)/PathConstraint.o \
	$(OBJDIR)/Event.o \
	$(OBJDIR)/ClippingAttachment.o \
	$(OBJDIR)/Slot.o \
	$(OBJDIR)/SkeletonBinary.o \
	$(OBJDIR)/AnimationStateData.o \
	$(OBJDIR)/Json.o \
	$(OBJDIR)/Triangulator.o \
	$(OBJDIR)/Skin.o \
	$(OBJDIR)/TransformConstraint.o \
	$(OBJDIR)/TransformConstraintData.o \
	$(OBJDIR)/EventData.o \
	$(OBJDIR)/extension.o \
	$(OBJDIR)/RegionAttachment.o \
	$(OBJDIR)/PathConstraintData.o \
	$(OBJDIR)/SkeletonData.o \
	$(OBJDIR)/Atlas.o \
	$(OBJDIR)/AtlasAttachmentLoader.o \
	$(OBJDIR)/SkeletonClipping.o \
	$(OBJDIR)/IkConstraint.o \
	$(OBJDIR)/BoneData.o \
	$(OBJDIR)/Array.o \
	$(OBJDIR)/Bone.o \
	$(OBJDIR)/IkConstraintData.o \
	$(OBJDIR)/Color.o \
	$(OBJDIR)/BoundingBoxAttachment.o \
	$(OBJDIR)/SlotData.o \
	$(OBJDIR)/PathAttachment.o \
	$(OBJDIR)/VertexAttachment.o \
	$(OBJDIR)/AnimationState.o \
	$(OBJDIR)/AttachmentLoader.o \
	$(OBJDIR)/PointAttachment.o \
	$(OBJDIR)/Attachment.o \
	$(OBJDIR)/SkeletonBounds.o \
	$(OBJDIR)/Skeleton.o \
	$(OBJDIR)/spine-sfml.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking DeusVultCore
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning DeusVultCore
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/InputManager.o: Core/ResourceManagers/InputManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ResourceManager.o: Core/ResourceManagers/ResourceManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MapManager.o: Core/ResourceManagers/MapManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EntityList.o: Core/ResourceManagers/EntityList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnimatedSprite.o: Core/Animation/AnimatedSprite.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SPRAnimation.o: Core/Animation/SPRAnimation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Game.o: Core/Common/Game.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Entity.o: Core/Common/Entity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GameMap.o: Core/Common/GameMap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/main.o: Core/Common/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Scripts.o: Core/Common/Scripts.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HUD.o: Core/HUD/HUD.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MovementComponent.o: Core/Components/MovementComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NpcComponent.o: Core/Components/NpcComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SensoryComponent.o: Core/Components/SensoryComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ControllerComponent.o: Core/Components/ControllerComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CombatComponent.o: Core/Components/CombatComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SpineComponent.o: Core/Components/SpineComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OutlineComponent.o: Core/Components/OutlineComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScriptComponent.o: Core/Components/ScriptComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SpriteComponent.o: Core/Components/SpriteComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InteractionComponent.o: Core/Components/InteractionComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TransformComponent.o: Core/Components/TransformComponent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MeshAttachment.o: spine/spine-c/spine-c/src/spine/MeshAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Animation.o: spine/spine-c/spine-c/src/spine/Animation.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkeletonJson.o: spine/spine-c/spine-c/src/spine/SkeletonJson.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PathConstraint.o: spine/spine-c/spine-c/src/spine/PathConstraint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Event.o: spine/spine-c/spine-c/src/spine/Event.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ClippingAttachment.o: spine/spine-c/spine-c/src/spine/ClippingAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Slot.o: spine/spine-c/spine-c/src/spine/Slot.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkeletonBinary.o: spine/spine-c/spine-c/src/spine/SkeletonBinary.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnimationStateData.o: spine/spine-c/spine-c/src/spine/AnimationStateData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Json.o: spine/spine-c/spine-c/src/spine/Json.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Triangulator.o: spine/spine-c/spine-c/src/spine/Triangulator.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Skin.o: spine/spine-c/spine-c/src/spine/Skin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TransformConstraint.o: spine/spine-c/spine-c/src/spine/TransformConstraint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TransformConstraintData.o: spine/spine-c/spine-c/src/spine/TransformConstraintData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EventData.o: spine/spine-c/spine-c/src/spine/EventData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/extension.o: spine/spine-c/spine-c/src/spine/extension.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RegionAttachment.o: spine/spine-c/spine-c/src/spine/RegionAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PathConstraintData.o: spine/spine-c/spine-c/src/spine/PathConstraintData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkeletonData.o: spine/spine-c/spine-c/src/spine/SkeletonData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Atlas.o: spine/spine-c/spine-c/src/spine/Atlas.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AtlasAttachmentLoader.o: spine/spine-c/spine-c/src/spine/AtlasAttachmentLoader.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkeletonClipping.o: spine/spine-c/spine-c/src/spine/SkeletonClipping.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/IkConstraint.o: spine/spine-c/spine-c/src/spine/IkConstraint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BoneData.o: spine/spine-c/spine-c/src/spine/BoneData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Array.o: spine/spine-c/spine-c/src/spine/Array.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Bone.o: spine/spine-c/spine-c/src/spine/Bone.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/IkConstraintData.o: spine/spine-c/spine-c/src/spine/IkConstraintData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Color.o: spine/spine-c/spine-c/src/spine/Color.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BoundingBoxAttachment.o: spine/spine-c/spine-c/src/spine/BoundingBoxAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SlotData.o: spine/spine-c/spine-c/src/spine/SlotData.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PathAttachment.o: spine/spine-c/spine-c/src/spine/PathAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VertexAttachment.o: spine/spine-c/spine-c/src/spine/VertexAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnimationState.o: spine/spine-c/spine-c/src/spine/AnimationState.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AttachmentLoader.o: spine/spine-c/spine-c/src/spine/AttachmentLoader.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PointAttachment.o: spine/spine-c/spine-c/src/spine/PointAttachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Attachment.o: spine/spine-c/spine-c/src/spine/Attachment.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkeletonBounds.o: spine/spine-c/spine-c/src/spine/SkeletonBounds.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Skeleton.o: spine/spine-c/spine-c/src/spine/Skeleton.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/spine-sfml.o: spine/spine-sfml/src/spine/spine-sfml.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
