# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := DeusVultCore DeusVultGame

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

DeusVultCore: 
	@echo "==== Building DeusVultCore ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f DeusVultCore.make

DeusVultGame: DeusVultCore
	@echo "==== Building DeusVultGame ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f DeusVultGame.make

clean:
	@${MAKE} --no-print-directory -C . -f DeusVultCore.make clean
	@${MAKE} --no-print-directory -C . -f DeusVultGame.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DeusVultCore"
	@echo "   DeusVultGame"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
